import type { CollectionConfig } from 'payload'
import { isAdmin } from '../access/isAdmin'
import { isAdminOrEditor } from '../access/isAdminOrEditor'
import { logCollectionChange, logCollectionDelete } from '../hooks/logActivity'
import { setTrackingUrl } from './orders-hooks/setTrackingUrl'
import { sendOrderStatusEmail } from '../hooks/sendOrderStatusEmail'

export const Orders: CollectionConfig = {
  slug: 'orders',
  access: {
    // Checkout uses local API and bypasses access control
    create: isAdminOrEditor,
    delete: isAdmin,
    read: ({ req: { user } }) => {
      if (!user) return false
      // Customers can only see their own orders
      if ((user as any)?.collection === 'customers') {
        return { customerEmail: { equals: (user as any).email } }
      }
      return true
    },
    update: isAdminOrEditor,
  },
  admin: {
    useAsTitle: 'orderNumber',
    defaultColumns: ['orderNumber', 'status', 'total', 'carrier', 'trackingNumber', 'customerEmail', 'createdAt'],
    group: 'Shop',
    description: 'Orders created via checkout are auto-populated. You can also create manual orders here.',
  },
  fields: [
    {
      name: 'orderNumber',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'Auto-generated by checkout (e.g. ORD-20260625-ABCD). Set manually for offline orders.',
      },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'pending',
      options: [
        { label: '⏳ Pending', value: 'pending' },
        { label: '💳 Paid', value: 'paid' },
        { label: '📦 Processing', value: 'processing' },
        { label: '🚚 Shipped', value: 'shipped' },
        { label: '✅ Delivered', value: 'delivered' },
        { label: '❌ Cancelled', value: 'cancelled' },
        { label: '↩️ Refunded', value: 'refunded' },
      ],
      admin: { position: 'sidebar' },
    },
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Items',
          fields: [
            {
              name: 'items',
              type: 'array',
              required: true,
              admin: {
                description: 'Products in this order. For checkout orders these are auto-filled.',
              },
              fields: [
                {
                  name: 'product',
                  type: 'relationship',
                  relationTo: 'products',
                  admin: { description: 'Link to the product (optional for manual/custom orders).' },
                },
                {
                  name: 'productTitle',
                  type: 'text',
                  required: true,
                  admin: { description: 'Product name as shown on the order (snapshot at time of purchase).' },
                },
                { name: 'variantName', type: 'text', label: 'Variant / Size' },
                {
                  name: 'quantity',
                  type: 'number',
                  required: true,
                  min: 1,
                  defaultValue: 1,
                },
                {
                  name: 'unitPrice',
                  type: 'number',
                  required: true,
                  admin: {
                    description: 'Price per unit in pence (e.g. 1999 = £19.99).',
                  },
                },
                {
                  name: 'lineTotal',
                  type: 'number',
                  required: true,
                  admin: {
                    description: 'Line total in pence (quantity × unit price).',
                  },
                },
              ],
            },
            {
              name: 'subtotal',
              type: 'number',
              label: 'Subtotal (pence)',
              admin: {
                description: 'Sum of all line items before shipping and discounts.',
                readOnly: true,
              },
            },
            {
              name: 'shippingCost',
              type: 'number',
              label: 'Shipping Cost (pence)',
              defaultValue: 0,
              admin: { readOnly: true },
            },
            {
              name: 'taxAmount',
              type: 'number',
              label: 'Tax/VAT Amount (pence)',
              defaultValue: 0,
              admin: {
                description: 'Total VAT amount. Extracted from prices if prices include tax.',
                readOnly: true,
              },
            },
            {
              name: 'taxRate',
              type: 'number',
              label: 'Effective Tax Rate (%)',
              admin: {
                description: 'Blended tax rate across all items. For display purposes.',
                readOnly: true,
              },
            },
            {
              name: 'taxBreakdown',
              type: 'json',
              label: 'Tax Breakdown',
              admin: {
                description: 'Per-rate tax breakdown (auto-generated). e.g. [{class: "standard", rate: 20, taxableAmount: 1000, taxAmount: 200}]',
                readOnly: true,
              },
            },
          ],
        },
        {
          label: 'Customer',
          fields: [
            {
              name: 'customerEmail',
              type: 'email',
              required: true,
              label: 'Customer Email',
            },
            {
              name: 'customerName',
              type: 'text',
              label: 'Customer Name',
            },
            {
              name: 'customer',
              type: 'relationship',
              relationTo: 'customers',
              label: 'Customer Account',
              admin: { description: 'Link to a registered customer account (optional).' },
            },
            {
              name: 'shippingAddress',
              type: 'group',
              label: 'Shipping Address',
              fields: [
                { name: 'line1', type: 'text', label: 'Address Line 1' },
                { name: 'line2', type: 'text', label: 'Address Line 2' },
                { name: 'city', type: 'text', label: 'City' },
                { name: 'county', type: 'text', label: 'County / State' },
                { name: 'postcode', type: 'text', label: 'Postcode / ZIP' },
                { name: 'country', type: 'text', label: 'Country' },
              ],
            },
          ],
        },
        {
          label: 'Payment',
          fields: [
            {
              name: 'total',
              type: 'number',
              required: true,
              label: 'Order Total (pence)',
              admin: {
                description: 'Grand total including tax, shipping, and discounts. In pence (e.g. 2499 = £24.99).',
              },
            },
            {
              name: 'discountCode',
              type: 'text',
              label: 'Discount Code',
              admin: {
                readOnly: true,
                description: 'Promo code applied to this order',
              },
            },
            {
              name: 'discountAmount',
              type: 'number',
              label: 'Discount Amount (pence)',
              admin: {
                readOnly: true,
                description: 'Discount applied in pence',
              },
            },
            {
              name: 'stripeSessionId',
              type: 'text',
              label: 'Stripe Session ID',
              admin: {
                readOnly: true,
                description: 'Auto-populated from Stripe checkout. Leave blank for manual orders.',
              },
            },
            {
              name: 'stripePaymentIntentId',
              type: 'text',
              label: 'Stripe Payment Intent ID',
              admin: {
                readOnly: true,
                description: 'Auto-populated from Stripe checkout.',
              },
            },
          ],
        },
        {
          label: 'Shipping',
          fields: [
            {
              name: 'carrier',
              type: 'select',
              label: 'Shipping Carrier',
              options: [
                // UK
                { label: 'Royal Mail (UK)', value: 'royal_mail' },
                { label: 'DPD (UK)', value: 'dpd_uk' },
                { label: 'Evri / Hermes (UK)', value: 'evri' },
                { label: 'DHL (UK)', value: 'dhl_uk' },
                { label: 'Parcelforce (UK)', value: 'parcelforce' },
                { label: 'Yodel (UK)', value: 'yodel' },
                { label: 'Amazon Logistics (UK)', value: 'amazon_uk' },
                // US
                { label: 'USPS (US)', value: 'usps' },
                { label: 'UPS (US)', value: 'ups' },
                { label: 'FedEx (US)', value: 'fedex' },
                { label: 'DHL (US)', value: 'dhl_us' },
                // International
                { label: 'DHL International', value: 'dhl_intl' },
              ],
              admin: {
                description: 'Select the shipping provider',
              },
            },
            {
              name: 'trackingNumber',
              type: 'text',
              label: 'Tracking Number',
              admin: {
                description: 'Enter the carrier tracking number',
              },
            },
            {
              name: 'trackingUrl',
              type: 'text',
              label: 'Tracking URL',
              admin: {
                readOnly: true,
                description: 'Auto-generated from carrier + tracking number',
              },
            },
            {
              name: 'shippedAt',
              type: 'date',
              label: 'Shipped Date',
              admin: {
                date: {
                  pickerAppearance: 'dayAndTime',
                },
              },
            },
            {
              name: 'deliveredAt',
              type: 'date',
              label: 'Delivered Date',
              admin: {
                date: {
                  pickerAppearance: 'dayAndTime',
                },
              },
            },
            {
              name: 'shippingNotes',
              type: 'textarea',
              label: 'Shipping Notes',
              admin: {
                description: 'e.g. "Left with neighbour", "Requires signature"',
              },
            },
          ],
        },
        {
          label: 'Notes',
          fields: [
            {
              name: 'notes',
              type: 'textarea',
              label: 'Internal Notes',
              admin: { description: 'Admin-only notes. Not shown to the customer.' },
            },
          ],
        },
        {
          label: 'Refunds',
          fields: [
            {
              name: 'refundAction',
              type: 'ui',
              admin: {
                components: {
                  Field: '@/components/RefundButton',
                },
              },
            },
            {
              name: 'totalRefunded',
              type: 'number',
              label: 'Total Refunded (pence)',
              defaultValue: 0,
              admin: {
                readOnly: true,
                description: 'Running total of all refunds issued for this order, in pence.',
              },
            },
            {
              name: 'refunds',
              type: 'array',
              label: 'Refund History',
              admin: {
                readOnly: true,
                description: 'History of all refunds issued for this order.',
              },
              fields: [
                {
                  name: 'stripeRefundId',
                  type: 'text',
                  label: 'Stripe Refund ID',
                  admin: { readOnly: true },
                },
                {
                  name: 'amount',
                  type: 'number',
                  label: 'Amount (pence)',
                  admin: { readOnly: true },
                },
                {
                  name: 'reason',
                  type: 'select',
                  label: 'Reason',
                  options: [
                    { label: 'Duplicate', value: 'duplicate' },
                    { label: 'Fraudulent', value: 'fraudulent' },
                    { label: 'Customer Request', value: 'requested_by_customer' },
                  ],
                  admin: { readOnly: true },
                },
                {
                  name: 'note',
                  type: 'text',
                  label: 'Internal Note',
                  admin: { readOnly: true },
                },
                {
                  name: 'refundedAt',
                  type: 'date',
                  label: 'Refunded At',
                  admin: { readOnly: true },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: 'invoiceActions',
      type: 'ui',
      admin: {
        components: {
          Field: '@/components/InvoiceButton',
        },
      },
    },
  ],
  hooks: {
    beforeChange: [setTrackingUrl],
    afterChange: [sendOrderStatusEmail, logCollectionChange],
    afterDelete: [logCollectionDelete],
  },
  timestamps: true,
}
